name: Android Build

on:
  push:
    branches: [ "g2path" ]
  pull_request:
    branches: [ "g2path" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          changelog: CHANGELOG.md
        env:
          # (required) GitHub token for creating GitHub Releases.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod 755 gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: upload file  
      uses: taiki-e/upload-rust-binary-action@v1
      with:
          # (required) Binary name (non-extension portion of filename) to build and upload.
        bin: ./app/build/outputs/apk/release/app-release-unsigned.apk
      env:
          # (required) GitHub token for uploading assets to GitHub Releases.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
